### PR TITLE
Added v2.0.0pre

### PR DESCRIPTION
**Pull request by davidzwa**
The prerelease for v2.0.1 which is a library renamed as mat-list-touch now. @ShankyTiwari I hope to hear from you.

### CODE REVIEW

**Comment by davidzwa** [comment]
Ah shoot, I see now that I renamed a lot to NgMatListSwipe instead of NgMatListTouch or MatListTouch, do you have any preference?

**Comment by davidzwa** [comment]
@ShankyTiwari I have discovered a couple of weird things. Once we update the list data, Angular throws a warning/error that the data changed after is was updated (@slideRow transition bind).

How do you normally update the list data?

**Comment by ShankyTiwari** [comment]
It works well, I have directly added you as a Collaborator.

**Comment by davidzwa** [comment]
Do appreciate it, at any moment if you dont like the direction: tell me!

**Comment by ShankyTiwari** [comment]
Sure, looking forward to your commits :)

**Comment by davidzwa** [comment]
I pushed to v2.0 branch, is not working but I want to give users something to look at.

Will come back to it later

**Comment by ShankyTiwari** [comment]
Hey sure, I appreciate your contributions. I am currently super busy with my interview preparation n all though I'll look into it.

Thanks a ton,

**Pull request closed without merging**
