### PR TITLE
Make generic, improve ease of use, remove awkward code

### PR DESCRIPTION
**Pull request by davidzwa**
- [x] Much more styling options
- [x] Separate swipe events (Left, Right) and Tap
- [x] Much less warning bloat, better initialisation (independency)
- [x] Better naming of variables
- [x] Better default styling... I have no idea why you did the 97%/98 width/height and margin stuff?

- [ ] Absolutely generic (not yet, because it still assumes certain colors names, property names is still static and transitions)
- [ ] Not a DataSource approach (look at MatTableDataSource, that stuff is super generic)

### CODE REVIEW

**Comment by davidzwa** [comment]
As example mapping of API real data (in my case an event Interface):
```
dataSource: IListDataSource<IEventSimple>[] = [];
...
response.Result.forEach(event => {
    this.dataSource.push({
        title: event.Name,
        description: event.Description,
        icon: this.typeToIcon(event.Type),
        data: event,
    });
});
```

and template code:

`<ng-mat-list-swipe [dataSource]="dataSource" [icon]="true"></ng-mat-list-swipe>`

much simpler, almost generic (the true generic approach would allow ng-template definitions like Angular Material Tables and thus the developer's own data definition without having to map that to a specific interface, maybe something for the future)

**Comment by ShankyTiwari** [comment]
Great! Thanks for the PR.

**Comment by ShankyTiwari** [comment]
I created this project year ago but after I never updated it. Actually it never came to my use.
So there are lot of things that can be improved.

**Comment by ShankyTiwari** [comment]
I took a clone of your repo, got below errors,
image

The project is created with Angular CLI 6 and I have Angular 8 installed, the dependencies need to be updated to Angular 8.

**Comment by davidzwa** [comment]
Thanks for getting back to me that fast. I will look into it!
Got some updates and will test the project separately (I was too lazy and wanted your feedback first).

I'm currently working on :
- predefined but optional colored left/right borders (as my app requires it)
- border radius during swipe 
- new animation like Android (after a succesful swipe, the swipe completes to 100% on my gmail app f.e.) 

Any other things you didnt get the time for?

**Comment by ShankyTiwari** [comment]
Hey, Thanks for the update.
Since you are changing a lot of stuff can I suggest you to convert this app pure Angular Library using [ng generate library](https://angular.io/guide/creating-libraries) if you have enough time!

Thanks,

**Comment by davidzwa** [comment]
Ah, good idea. I just started afresh and added a library. PR coming today or tomorrow.

**Comment by ShankyTiwari** [comment]
Thanks, mate.

**Comment by davidzwa** [comment]
Hmm, Im getting import errors when I put the code in a library with the link you sent. Have you done it before?

image

**Comment by ShankyTiwari** [comment]
Yes, I have for [this module](https://github.com/ShankyTiwari/ng-material-multilevel-menu), I use this module in my 4 to 5 projects, so I had to.  I think you will find [this commit](https://github.com/ShankyTiwari/ng-material-multilevel-menu/commit/761fa16e16f6c68475f8190a1d79dca37cdf04d2) helpful.

Steps I followed:
1. I created an entirely new project and added the remote git there.
2. Copy pasted the required code from the current repo.
3. Pushed it.

Becoz changing everything in the current repo will very cumbersome. Hope this reply helps you.
Thanks.

**Comment by davidzwa** [comment]
I've followed the steps and will make a PR now. Also I've changed the project name to something more easily hit on google/npm, upped the version to 2.0.0 (so you can update the breaking changes whenever you are able to).

**Comment by davidzwa** [comment]
@ShankyTiwari did you have the time to look at the other pull request? Is it working for you or shall I make a new npm package?

**Comment by ShankyTiwari** [comment]
@davidzwa , sorry for the delay i'll look into it tonight for sure.

**Pull request closed without merging**
